version: "3.8"

services:
  backend:
    build: ./backend
    container_name: "trade_informer_backend"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    command: sh -c 'go mod tidy && air'
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: "trade_informer_frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend

  db:
    image: mysql:8.2
    container_name: "trade_informer_db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
